apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: perfsonar-deployment
  labels:
    app: perfsonar
spec:
  replicas: 3
  selector:
    matchLabels:
      app: perfsonar
  template:
    metadata:
      labels:
        app: perfsonar
    spec:
      hostNetwork: true
      containers:
      - name: perfsonar
        image: perfsonar/tools
